# Provided data
import csv


provided_data = [
    ('PHDK', 'PHDEAK'),
    ('CHBG', 'CHHOETEAL BANGKOUNEANGO'),
    ('CHBR', 'CHHOETEAL BRENG'),
    ('CHTR', 'CHHOETEAL CHHNGAR'),
    ('CHMI', 'CHHOETEAL MOSAU'),
    ('CHRH', 'CHORCHONG'),
    ('CRMS', 'CHRASMAS'),
    ('KKMS', 'KOKI MOSAU'),
    ('KKPN', 'KOKI PHNONG\KAMNHAN'),
    ('LMBI', 'LUMBOR'),
    ('PCEK', 'PHCEK'),
    ('TBEG', 'TBENG'),
    ('KHOV', 'KCHOV/KAMLENG'),
    ('KKDK', 'KOKI DEK'),
    ('KKKS', 'KOKI KHASAC'),
    ('KKTM', 'KOKI THMOR'),
    ('PPEL', 'POPEL'),
    ('RINM', 'RAING PHNOM'),
    ('TRLT', 'TRORLAT'),
    ('ANKM', 'ANGKOT KHMAU'),
    ('ATTT', 'ATITH/NEANG PHOR EK'),
    ('BENG', 'BENG'),
    ('BSNK', 'BOSNEAK'),
    ('CHBK', 'CHAM BAK'),
    ('CHKM', 'CHHOEU KHMAV/NEANG KHMAV'),
    ('CHKO', 'CHOEUNG KO'),
    ('CHKR', 'CHAN KRASNA'),
    ('CHLK', 'CHHLIK'),
    ('CHMC', 'CHHAM CHHA'),
    ('CHTP', 'CHAN TOUM PEANG'),
    ('DCSP', 'DONCHERM'),
    ('DYKL', 'DEY KHLA'),
    ('HUDN', 'HOUN DAN/MOREASPREOUPHNOM'),
    ('KMPR', 'KOMPENG REACH'),
    ('KRAY', 'KRAY'),
    ('KREL', 'KROEL'),
    ('KRKO', 'KRORKORS'),
    ('KRPM', 'KRORNHOUNG'),
    ('KRYS', 'KRAY SAR'),
    ('MASK', 'MEYSAK'),
    ('NNON', 'NEANG NOUN'),
    ('PRDL', 'PRAM DOMLENG'),
    ('PRLO', 'PRO LOUP'),
    ('PRNG', 'PRING/KRORB BEK'),
    ('SKRM', 'SOKROM'),
    ('SMPN', 'SAM PONG'),
    ('SRAL', 'SRAL'),
    ('SRKR', 'SROL KRAHAM'),
    ('SRLO', 'SRORLAO'),
    ('SROL', 'SROL SAR'),
    ('SWPR', 'SVAY PREY'),
    ('SYCR', 'SVAY CHAM REANG'),
    ('TAUR', 'TAOUR'),
    ('TEPI', 'TEP PHIROU'),
    ('THNR', 'THNONG KROHORM'),
    ('THNS', 'THNONG SOR'),
    ('TRTM', 'TRORP TOM'),
    ('TRYG', 'TROR YING'),
    ('TTRV', 'TATRAV'),
    ('ANKN', 'ANGKANH'),
    ('ANKT', 'ANGKAT TMAAT'),
    ('ANOM', 'ANGKRANG PHNOM'),
    ('ATNG', 'ATEANG/ROTEANG'),
    ('BADM', 'BAK DERM'),
    ('BAKG', 'BANGKANG'),
    ('BDNG', 'BAKDORNG'),
    ('BELY', 'BELOY'),
    ('BKSV', 'BANGKEOU SVA'),
    ('BNKO', 'BAG KHEOU'),
    ('BYPV', 'BAY POU VAING'),
    ('CASA', 'KHCHOENG'),
    ('CCHB', 'CHOEUNG CHAB'),
    ('CHMK', 'CHAMRIEK'),
    ('CHNY', 'CHORNY'),
    ('CHPL', 'CHHOE PHLOEUNG'),
    ('CHRK', 'CHRAKENG'),
    ('CHRM', 'CHANG KONG ROMEANG'),
    ('CHRS', 'CHREIS'),
    ('CHUT', 'CHORNG UOR THMAT'),
    ('CKTM', 'CHEK TUM'),
    ('CREY', 'CHREY'),
    ('DKOR', 'DONGKOR'),
    ('DOKM', 'DOK MEY'),
    ('HISN', 'HAISANH/NGAYSANG/CHANSAR'),
    ('KAOM', 'KANGSENGPHNOM'),
    ('KCAS', 'KCHAS'),
    ('KDAG', 'KANN DEANG'),
    ('KDCH', 'KDURCH'),
    ('KDOL', 'KDOL'),
    ('KES', 'KES'),
    ('KKCM', 'KONG KANGCHHMOL'),
    ('KKGN', 'KONG KANGNHY'),
    ('KKOM', 'KONG KANGPHNOM'),
    ('KNDL', 'KANNDOL'),
    ('KNPR', 'KHNOR PREY'),
    ('KRAG', 'KRANG'),
    ('KRAS', 'KREAS'),
    ('KRBO', 'KRORBAO'),
    ('KRLA', 'KRORLANH'),
    ('KRON', 'KRONG'),
    ('KTOM', 'KHTOM'),
    ('KWAV', 'KHVAO'),
    ('LGNG', 'LO NGIENG'),
    ('MAKG', 'MAK BREING'),
    ('MAKP', 'MAK PRANG'),
    ('MAKU', 'MAK KLOEU'),
    ('MNPR', 'MEAN PREY'),
    ('NENS', 'NEANG SAR'),
    ('PANG', 'PANG'),
    ('PHNV', 'PHNHEAV'),
    ('PHON', 'PHAONG'),
    ('PHUT', 'PROR HOUT'),
    ('PLON', 'PLONG'),
    ('PNAG', 'PHNEANG'),
    ('PNGS', 'PHNGEAS'),
    ('POBY', 'POPUOL BAY'),
    ('POCV', 'PON SVAR'),
    ('POKH', 'POPEA KHE'),
    ('PONR', 'PONG RO'),
    ('PPTH', 'POPULTHMOR'),
    ('PPUL', 'PHNEL/POPOUL'),
    ('PRPN', 'PREAS PHNOV/SOMBOK KROHOM'),
    ('PRUS', 'PROUS'),
    ('PYPK', 'PHKAI PROEK'),
    ('RAIT', 'RAING TOEK'),
    ('ROKA', 'ROKA'),
    ('RUNG', 'ROUNG'),
    ('SABL', 'SAMBOUR LOVENG'),
    ('SARG', 'SAM RONG'),
    ('SBMS', 'SAMBOUR MEAS'),
    ('SDAV', 'SDAV'),
    ('SDEY', 'SDEY'),
    ('SLEN', 'SLENG'),
    ('SMCH', 'SMACH'),
    ('SME', 'SME'),
    ('SMKB', 'SMA KRABEY'),
    ('SNAY', 'SNAY'),
    ('SNOL', 'SNUOL'),
    ('SOUY', 'SOURY'),
    ('SPOR', 'SOM POR'),
    ('SPPY', 'SPEOU PREY'),
    ('SPTK', 'SPEOU TEK'),
    ('SRKM', 'SRAKOM'),
    ('SVAK', 'SVAY SVAK'),
    ('SVCT', 'SVAY CHANTI'),
    ('SVPT', 'SVAY PONGTRONG'),
    ('TKOV', 'TKOV'),
    ('TLOK', 'THLOK'),
    ('TOLP', 'TOUNLORP'),
    ('TPOG', 'TOM POUNG'),
    ('TRAG', 'TRANG'),
    ('TREN', 'TRA MENG'),
    ('TRMN', 'TRORMOUNG'),
    ('TRSK', 'TRORMOUNGSEK'),
    ('WYNG', 'VOR YONG'),
    ('ACSA', 'ACH SAT'),
    ('ADCH', 'ACHDERK'),
    ('AKSL', 'ANGKEA SEL'),
    ('AMBB', 'AMBENG BEK'),
    ('AMCN', 'AMBENG CHAN'),
    ('AMPI', 'AMPIL TOEUK PREY'),
    ('ANCH', 'ANGKOCH'),
    ('ANKB', 'ANGKEA BOS'),
    ('ANRD', 'ANGRE DEK'),
    ('APEN', 'APHEAN'),
    ('ATES', 'ATES'),
    ('ATSR', 'ANNTUNG SOR'),
    ('BAKK', 'BANGKONG KENGKONG'),
    ('BAKP', 'BAKPAO'),
    ('BBOK', 'BOR BORK'),
    ('BOPR', 'BO PROEUK'),
    ('BRCH', 'BROR CHOK'),
    ('BTIL', 'BATPHTIL'),
    ('CABB', 'CHAM BAK BARAING'),
    ('CHCK', 'CHHOENG CHKER'),
    ('CHEK', 'CHANG ENG SEK'),
    ('CHHA', 'CHHAR'),
    ('CHHU', 'CHHOM POU PREY'),
    ('CHKG', 'CHEUNG KRORVAING'),
    ('CHKP', 'CHUNGKONG PHON'),
    ('CHKU', 'CHEUNG KRAPEU'),
    ('CHLS', 'CHORNLOS'),
    ('CHNA', 'CHANG NANG'),
    ('CHNO', 'CHNOK'),
    ('CHOV', 'CHOV'),
    ('CHPS', 'CHHOETEAL PREUS'),
    ('CHTU', 'CHNOK TROU'),
    ('CTES', 'CHORNTESPLOUK'),
    ('DAKD', 'DANG KEAP KDAM'),
    ('DGPR', 'DANGKEABPROEUS'),
    ('DKPO', 'DOKPO'),
    ('DNKY', 'DOUNKAY'),
    ('DRDV', 'DORNG DAV'),
    ('DYSP', 'DEY SAMPOCH'),
    ('EPSH', 'EYSEIPHSAM SRACH'),
    ('KACL', 'KACHEAL'),
    ('KAKU', 'KAKHUCH'),
    ('KANA', 'KANA'),
    ('KANE', 'KANER'),
    ('KANT', 'KANTOUT PREY'),
    ('KATG', 'KATOUNG'),
    ('KAYK', 'KA YOUK'),
    ('KBAL KRORLORNG', 'KBAL KRORLORNG'),
    ('KBDA', 'KANCHOEU BEY DACH'),
    ('KBDK', 'KBAL DERK'),
    ('KBKK', 'KROBAO KHEK'),
    ('KCHP', 'KA CHIEP'),
    ('KDCE', 'KANDAB CHANG ET'),
    ('KDCK', 'KDOR COMBROK'),
    ('KHMA', 'KHANNMA'),
    ('KHNH', 'KHNHE'),
    ('KHOS', 'KHOS'),
    ('KHTN', 'KHTING'),
    ('KHVG', 'KHVENG'),
    ('KKAL', 'KALKAL'),
    ('KKKK', 'KALAP'),
    ('KKLG', 'KBAL KRORLORNG'),
    ('KLIG', 'KLING'),
    ('KLNG', 'KLOUNG'),
    ('KLPO', 'KLENG POR'),
    ('KMPT', 'KOM PERT'),
    ('KNAL', 'KNALL'),
    ('KNAY', 'KNAY MORN'),
    ('KODK', 'KORNDORK'),
    ('KOKH', 'KON KHMOM'),
    ('KOMT', 'KOKTMAT'),
    ('KOMY', 'KO MOUY'),
    ('KORK', 'KORK'),
    ('KOTT', 'KORTHET'),
    ('KRAK', 'KRORCHORK ANDERK'),
    ('KREG', 'KROENG'),
    ('KREM', 'KROR EM'),
    ('KRMN', 'KROR MOURN'),
    ('KROH', 'KROCH PREY'),
    ('KRSR', 'KRORNG SOEUR'),
    ('KRUS', 'KHOES REOUS'),
    ('KRVN', 'KRORVANN'),
    ('KTIT', 'KTITH'),
    ('LORT', 'LORT'),
    ('LORV', 'LOR VEA'),
    ('LOVG', 'LORVING'),
    ('LRLT', 'LORLOT'),
    ('MADN', 'MADEHN'),
    ('MDAS', 'MADEHN MEAS'),
    ('MMAG', 'MOR MANG'),
    ('MTYK', 'MLOUTRAYOUK'),
    ('NGOK', 'NGOK'),
    ('NHAM', 'NHAM'),
    ('NIV', 'NIV'),
    ('ONLK', 'ONLOK PHOR EM'),
    ('PAGA', 'PA NGAB'),
    ('PAGS', 'PA NGES'),
    ('PECH', 'PECH CHANGVA'),
    ('PHLG', 'PHLANG'),
    ('PHMA', 'PHNERK CHMA'),
    ('PHNO', 'PHNOM PHNERNG'),
    ('PHOR', 'PHOR'),
    ('PLNG', 'PLOV NEANG'),
    ('PLOG', 'PLUOUNG'),
    ('PLOK', 'PLONG KEOV'),
    ('PLOR', 'PLOR'),
    ('PLPH', 'PLOV SOMPOUCH'),
    ('PMVG', 'PROMOY VIENG'),
    ('PNKP', 'PHNEK PREAP'),
    ('PNOM', 'PON ORMBORK'),
    ('POCH', 'POUCH'),
    ('POPL', 'PO PLEAR'),
    ('POUN', 'POUN'),
    ('PPPR', 'POPLEA PRUES'),
    ('PPVK', 'POPOULVAK'),
    ('PREL', 'PREAL'),
    ('PROM', 'PROMAT KHLAKMOM'),
    ('PROM', 'PROUM'),
    ('RANG', 'RAING'),
    ('ROCG', 'ROM CHORNG'),
    ('RODL', 'ROMDOUL'),
    ('ROML', 'ROMLEANG'),
    ('ROTY', 'ROMENGTHA NGE0Y'),
    ('ROVN', 'ROVIENG'),
    ('RPCK', 'ROMPEAT CHROUK'),
    ('SADA', 'SANDA'),
    ('SAHA', 'SANG HA'),
    ('SAND', 'SANDAN'),
    ('SANK', 'SANG KE'),
    ('SAVP', 'SANGVA PICH'),
    ('SBTS', 'SAMBOUR TES'),
    ('SEMN', 'SEMORN\ ROL'),
    ('SKPL', 'SLAKRORPOUL'),
    ('SLCH', 'SLA KCHEY'),
    ('SLET', 'SLOEK LO ET'),
    ('SLNG', 'SOM LEANG'),
    ('SOPI', 'SOPHY'),
    ('SREG', 'CHHKER SRERNG'),
    ('SRMO', 'SRORMOR'),
    ('TAPL', 'TAPIL'),
    ('TBOT', 'TABORT'),
    ('TENG', 'TENG'),
    ('THME', 'THMEAS'),
    ('THNO', 'THNOT PRENG'),
    ('THTR', 'THMENH TREY'),
    ('TMAK', 'TLERM ANNDERK'),
    ('TNIV', 'TAONIV'),
    ('TOUK', 'TOUK'),
    ('TRBL', 'TROR ORL'),
    ('TRCU', 'TRA BEK CHOU'),
    ('TREL', 'TREAL'),
    ('TROG', 'TRORNG'),
    ('TRSK', 'TRORSEK / TRAMKANG'),
    ('TRYA', 'TROR YAK'),
    ('TRYG', 'TROR YORNG'),
    ('TTPY', 'TOTIM PREY'),
    ('UNKN', 'UNKNOWN'),
    ('VEAY', 'VEAY'),
    ('VOEG', 'VOENG'),
    ('YEAM', 'YEAM'),
    ('YOUK', 'YOUK'),
    ('KHLG', 'KHLONG'),
    ('TRAC', 'TRACH')
]

# Create a list to store the repeated data
repeated_data = []

# Repeat the provided data until it reaches 50,000 rows
while len(repeated_data) < 50000:
    repeated_data.extend(provided_data)

# Truncate the excess rows
repeated_data = repeated_data[:50000]

# Writing the data to the CSV file
with open('data.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['SPECODE', 'Local-Name'])
    writer.writerows(repeated_data)

print("Data successfully written to data.csv")